# Generated by Django 3.2.5 on 2021-09-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloPrincipal', models.CharField(max_length=30)),
                ('palabrasCambiantes', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=10)),
                ('subtituloTextp', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'titulo',
                'verbose_name_plural': 'titulos',
            },
        ),
    ]
