# Generated by Django 3.2.5 on 2021-09-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulos',
            name='palabrasCambiantes',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='titulos',
            name='subtitulo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='titulos',
            name='subtituloTextp',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='titulos',
            name='tituloPrincipal',
            field=models.CharField(max_length=80),
        ),
    ]
