# Generated by Django 3.2.5 on 2021-09-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0004_auto_20210901_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('subtitulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Sobre Nosotros',
            },
        ),
    ]
