# Generated by Django 3.2.5 on 2021-09-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0005_sobrenosotros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sobrenosotros',
            options={'verbose_name': 'Sobre Nosotro'},
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='contenido',
            field=models.TextField(max_length=100),
        ),
    ]
