# Generated by Django 3.2.5 on 2021-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0008_alter_sobrenosotros_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrenosotros',
            name='imagenPrincipal',
            field=models.ImageField(default='wasd', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sobrenosotros',
            name='imagenSecundaria',
            field=models.ImageField(default='wasd', upload_to=''),
            preserve_default=False,
        ),
    ]
