# Generated by Django 3.2.5 on 2021-09-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0009_auto_20210901_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('contenido', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
