# Generated by Django 3.2.5 on 2021-09-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0010_especiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descripcion', models.TextField(max_length=200)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
                ('tipo', models.CharField(choices=[('Entradas', 'Entradas'), ('Plato Principal', 'Principal'), ('Postres', 'Postres'), ('Bebidas', 'Bebidas')], max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.AlterModelOptions(
            name='especiales',
            options={'verbose_name': 'Especiale'},
        ),
    ]
