# Generated by Django 3.2.5 on 2021-09-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0011_auto_20210902_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='descripcion',
            field=models.CharField(max_length=45),
        ),
    ]
