# Generated by Django 3.2.5 on 2021-09-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0012_alter_menu_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='descripcion2',
            field=models.CharField(default='que rico', max_length=45),
            preserve_default=False,
        ),
    ]
