# Generated by Django 3.2.5 on 2021-09-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0013_menu_descripcion2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen1', models.ImageField(upload_to='')),
                ('imagen2', models.ImageField(upload_to='')),
                ('imagen3', models.ImageField(upload_to='')),
                ('imagen4', models.ImageField(upload_to='')),
                ('imagen5', models.ImageField(upload_to='')),
                ('imagen6', models.ImageField(upload_to='')),
                ('imagen7', models.ImageField(upload_to='')),
                ('imagen8', models.ImageField(upload_to='')),
                ('imagen9', models.ImageField(upload_to='')),
                ('imagen10', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Galeria',
            },
        ),
    ]
