# Generated by Django 3.2.5 on 2021-09-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0016_novedades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=300)),
                ('facebook', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=30)),
                ('instagram', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Redes',
            },
        ),
    ]
