# Generated by Django 3.2.5 on 2021-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0018_auto_20210902_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='redes',
            name='facebook',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='redes',
            name='instagram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='redes',
            name='twitter',
            field=models.CharField(max_length=100),
        ),
    ]
