# Generated by Django 3.2.5 on 2021-09-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0019_auto_20210902_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.CharField(max_length=100)),
                ('martes', models.CharField(max_length=100)),
                ('miercoles', models.CharField(max_length=100)),
                ('jueves', models.CharField(max_length=100)),
                ('viernes', models.CharField(max_length=100)),
                ('sabado', models.CharField(max_length=100)),
                ('domingo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Horarios',
            },
        ),
    ]
