# Generated by Django 3.2.5 on 2021-09-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0021_remove_titulos_seleccionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especiales',
            name='imagen',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen_1',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen_10',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen_2',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen_3',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen_4',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen_5',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen_6',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen_7',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen_8',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen_9',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='novedades',
            name='imagen',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='imagenPrincipal',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='imagenSecundaria',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
    ]
